### ISSUE TITLE
 Level viewer

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#154]
# Level viewer

This is a __really__ long term project but I already started the basics of it.

We need to load given w2w then:
```
eg.: kaer_morhen.w2w
CGameWorld -> terrainClipMap ->  CClipMap #2 -> tiles -> all the terrain tiles
CMaterialGraph #1	-> pixelParameters	->	stars_cube -> the skybox w2cube
```
We can use irrlich's terrain renderer to acomplish this.
TODO:
  - [x] Implement basic terrain rendering in Irrlich
  - [x] Basic skybox rendering
  - [x] Basic model loader
  - [ ] Load the textures of given w2terr
  - [ ] Load the heightmap  of given w2terr
  - [ ] Load the controlmap  of given w2terr
  - [ ] Load the layers of given w2w
  - [ ] Implement blockdata and patchhash reverse lookup
  - [ ] Stich together multiple terrain tiles
  - [ ] Find objects in given area
  - [ ] Transform coordinates of CSectordata and load the model 
We need to load the terrain then given the layers we can probably load the objects in the area.
***
Current state:
![image](https://user-images.githubusercontent.com/6411732/78306801-8c485d00-7544-11ea-9049-5055b8c4657d.png)

**Comment by vonLeebpl** [comment]
Loading textures should be easy, heght map - I saw some examples on irrlicht site. The rest I have no clue.
