### ISSUE TITLE
The Last of Ub - Part Two

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#167]
**Is your feature request related to a problem? Please describe.**
The structure of all tw3 classes have been figured out, what is left to close this issue for good is figuring out the last scattered unknown variables in all classes. we just don't know the names of them.

BYTE ARRAYS: Priority-A

- [x] EntityHandle: variable number of bytes (mostly 0x00)
- [ ] CIndexed2dArray: unimportant meme class
- [ ] CCameraCompressedPose: only present in one file: \animations\camera\camera_animations.w2anims
- [ ] CPhysicalCollision: some remaining bytes
- [ ] CAreaComponent: bufferdata
- [ ] CCookedExplorations: some included file
- [ ] CGenericGrassMask: grassmaskdata
- [ ] CSwarmCellMap: first 10 bytes
- [ ] CSectorData: SBlockData: every 2nd file has some bytes left
- [ ] CMesh: SMeshBlock5: some remaining bytes
- [ ] CUmbraTile: no idea
NAMES OF VARIABLES: Priority-B

- [ ] TBC

**Comment by Traderain** [comment]
Is this list complete? CParticleEmitter and such is missing as well? Redexp and naviobstacles etc?

**Comment by rfuzzo** [comment]
Unknown Bytes;
- [ ] w2animev: CExtAnimEventsFile 55.96%
- [ ] w3occlusion: CUmbraTile 98.47%
- [ ] w2l CSectorData 99.92%
- [ ] w2anims:  CSkeletalAnimationSet 98.29%
- [ ] w2anims:  CCameraCompressedPose 52.68%

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
