### ISSUE TITLE
WPF Refactor

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#169]
Refactor the project to proper MVVM and WPF:
**PRE**
- [x] setup MVVM structure for existing forms in Winforms
- [x] Redesign xamls for the forms in Winforms

**MAIN**
- [x] Remake Dialogs/UserControls in WPF
- [x] Remake simple forms in WPF (no MVVM)

**Resources**

- AvalonDock
- Ninject

***
@rfuzzo already started the work on this
We need to redesign nearly everything so it's gonna be pretty horrible.  
We should porbably do this ASAP so we don't make new forms that need to be converted.

**Comment by rfuzzo** [comment]
**MVVM Status**

**Forms**
- [ ] Bulk Editor
- [ ] Cr2w Document
- [ ] Import Utility
- [ ] Main
- [ ] ModExplorer
- [ ] OtherDiocument
- [ ] Radish
- [ ] Anims
- [ ] Asset Browser
- [ ] ChunkFLowDiagram
- [ ] frmChunkList
- [ ] frmChunkProperties
- [ ] frmConsole
- [ ] frmCR2WtoText
- [ ] frmCreateInstaller.cs
- [ ] frmDebug.cs
- [ ] frmEmbeddedFiles.cs
- [ ] frmHexEditorView.cs
- [ ] frmInstallPackage.cs
- [ ] frmJournalEditor.cs
- [ ] frmMenuCreator.cs
- [ ] frmMimics.cs
- [ ] frmMusicPlayer.cs
- [ ] frmSaveEditor.cs
- [ ] frmScriptEditor.cs
- [ ] frmSettings.cs
- [ ] frmStringsGui.cs
- [ ] frmStringsGuiImporter.cs
- [ ] frmWelcome.cs

**UserControls**
- [ ] remake in WPF

**Dialogs**
- [ ] remake in WPF

**Comment by rfuzzo** [comment]
Started a branch here: 
[18fd3f491f56dfa0e13e65daac121f1b8b0023f0](https://github.com/Traderain/Wolven-kit/commit/18fd3f491f56dfa0e13e65daac121f1b8b0023f0)

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)

**Comment by Traderain** [comment]
Updated the remaining form list

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ProgressOverView](https://trello.com/c/wpKmfUCz/115-progressoverview)

**Comment by rfuzzo** [comment]
well this is done.
