### ISSUE TITLE
Proper string editing

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#254]
**Is your feature request related to a problem? Please describe.**
Currently the string editing experience is horrible.
![image](https://user-images.githubusercontent.com/6411732/96310296-67f72e00-1007-11eb-9ebd-bb19c3f316fb.png)
![image](https://user-images.githubusercontent.com/6411732/96310330-76dde080-1007-11eb-9108-5a725f49658c.png)

**Describe the solution you'd like**
- [ ] Proper control when editing cr2w files so:
  - [ ] Combobox where you can pick an existing line by searching and the id thing is completely hidden from the user
  - [ ] The first item of the combobox is called <[Add new  string]> which if you select, a dialog pops up to input a line.
- [ ] Some better thing to show the currently encoded string which works properly
- [ ] A form where you can quickly search strings/add new one and when you press enter it copies the id so you can add it in your scripts
- [ ] Some way to automatically assign mod id, idk check a git repo where people can pr the ids or something like ``sumbytes(md5{modname}) % stringidspacelength``  
***
The main idea is that you don't need to think about the whole id thing. You just set values in the files and copy the values you need into your scripts and you don't need to worry about anything.

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
