### ISSUE TITLE
Tweak DB support 

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#539]
Add a very basic tweak dB support to Wkit:

- [x] a standard folder in the project called tweakDB
- [x] A button “create new file” > tweak file which creates an empty file in the tweakDB folder
- [x] A text editor to edit the tweak files (or opening in external editor: VSCode)
- [x] When packing: cook files in tweakDB folder and deploy cooked DB to game folder optionally overwriting

**Comment by WopsS** [comment]
Are we going to create our own language for TweakDB and maybe use files named `tweak`? Or we will use some kind of JSON?

**Comment by Traderain** [comment]
How about yaml with .tweak extension?

**Comment by WSSDude420** [comment]
Dont like yaml personally :D

**Comment by WopsS** [comment]
YAML sounds good, might be better than creating our own grammar but others might not like it.

**Comment by rfuzzo** [comment]
Idea: independent of yaml or Json, if we add some basic text editor to Wkit that supports .tweak files, add a custom snippet gallery in the ribbon. 
e.g. a Dropdown menu like MS word with some templates: add new item template, add new ability template etc 

This concept can also apply to the same editor when editing .redscript files: templates for wrapping methods etc (see #538 )

**Comment by Offline-R503B** [comment]
> Idea: independent of yaml or Json, if we add some basic text editor to Wkit that supports .tweak files, add a custom snippet gallery in the ribbon.
> e.g. a Dropdown menu like MS word with some templates: add new item template, add new ability template etc
> 
> This concept can also apply to the same editor when editing .redscript files: templates for wrapping methods etc (see #538 )

You mean like the code editor 🦘

**Comment by rfuzzo** [comment]
> 
> 
> > Idea: independent of yaml or Json, if we add some basic text editor to Wkit that supports .tweak files, add a custom snippet gallery in the ribbon.
> > e.g. a Dropdown menu like MS word with some templates: add new item template, add new ability template etc
> > This concept can also apply to the same editor when editing .redscript files: templates for wrapping methods etc (see #538 )
> 
> You mean like the code editor 🦘

I mean we can use the same View (Editor) for .tweak and for .reds files

**Comment by WopsS** [comment]
## Problem

Creating a custom TweakDB is currently not possible using the existing tools, as of now modders can only edit the database using [CET](https://github.com/yamashi/CyberEngineTweaks), making them dependent on it, this is a good solution for mods that do more than adding new resources to the game (textures, models, etc.), but it is not optimal for archive-only mods.

## Solution

The problem can be solved using two solutions:

1. The first solution is to edit the current TweakDB file and add the necessary flats/records in it before the game starts, as [redscript](https://github.com/jac3km4/redscript).
2. Creating "delta" TweakDBs and have a third-party plugin to load them when the game starts.

## Proposal

Creating a tool that creates a "delta" TweakDB, a custom plugin to load TweakDBs is already available ([TweakDBext](https://github.com/WopsS/TweakDBext)).

For an initial prototype of this tool I would try to achieve the bare minimum in writing a TweakDB file, that means:

- Available only programmatically, no parsing / GUI for now.
- Only supporting flats, no records, queries, groups.

The final tools should fully support all features of a TweakDB, writing flats, records, queries and groups.

Future features can include:

- A parser for `tweak` files (or name them differently).
- A GUI in WolvenKit application.

What do you think about this and how should we handle it? I know @flibX0r is also working on a tool with the same goal.
