### ISSUE TITLE
Tracking TodoExceptions on the develop branch

### ISSUE THREAD

**Issue by jackhumbert** [WolvenKit/WolvenKit#636]
Not sure if there's a better way to track these, but here's a list of all the exceptions @ja-to & I could find in the project - feel free to check them off as they're addressed/handled:

**Critical Issues**

Prevents any mesh export
* [x] [MeshTools.cs#L986: TodoException("");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Tools/MeshTools.cs#L986)

**Unknown Impact**
* [ ] [ChunkPropertyViewModel.cs#L124: TodoException("Color conversion");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.App/ViewModels/Shell/ChunkPropertyViewModel.cs#L124)
* [ ] [RedExportDto.cs#L27: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/Conversion/RedExportDto.cs#L27)
* [ ] [RedExportDto.cs#L45: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/Conversion/RedExportDto.cs#L45)
* [ ] [CompiledPackage.cs#L173: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/RED4/Compiled/CompiledPackage.cs#L173)
* [ ] [CompiledPackage.cs#L192: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/RED4/Compiled/CompiledPackage.cs#L192)
* [ ] [CompiledPackage.cs#L325: TodoException("fix everything");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/RED4/Compiled/CompiledPackage.cs#L325)
* [ ] [CompiledPackage.cs#L383: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/RED4/Compiled/CompiledPackage.cs#L383)
* [ ] [CompiledPackage.cs#L403: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Common/RED4/Compiled/CompiledPackage.cs#L403)
* [x] [Rebuild.cs#L33: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Rebuild.cs#L33)
* [ ] [Rebuild.cs#L74: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Rebuild.cs#L74)
* [x] [DumpTask.cs#L201: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Tasks/DumpTask.cs#L201)
* [ ] [MaterialTools.cs#L201: TodoException("get import info from cr2w file?");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Tools/MaterialTools.cs#L201)
* [ ] [MaterialTools.cs#L604: TodoException(nameof(CMaterialParameterStructBuffer));](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Tools/MaterialTools.cs#L604)
* [ ] [MaterialTools.cs#L693: TodoException(nameof(CMaterialParameterStructBuffer));](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Tools/MaterialTools.cs#L693)
* [x] [Uncook.cs#L581: TodoException("get all buffers");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Uncook.cs#L581)
* [ ] [CR2WReader.cs#L113: TodoException($"Invalid default val for: "{RedReflection.GetRedTypeFromCSType(cls.GetType())}.{varname}"");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.cs#L113)
* [ ] [CR2WReader.cs#L127: TodoException("ReadSharedDataBuffer");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.cs#L127)
* [ ] [CR2WReader.cs#L141: TodoException("ReadSharedDataBuffer");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.cs#L141)
* [ ] [CR2WReader.File.cs#L102: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L102)
* [ ] [CR2WReader.File.cs#L136: TodoException("Unused buffer");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L136)
* [ ] [CR2WReader.File.cs#L154: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L154)
* [ ] [CR2WReader.File.cs#L159: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L159)
* [ ] [CR2WReader.File.cs#L174: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L174)
* [ ] [CR2WReader.File.cs#L207: TodoException($"Chunk size mismatch");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L207)
* [ ] [CR2WReader.File.cs#L234: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WReader.File.cs#L234)
* [ ] [CR2WWriter.File.cs#L234: TodoException("Invalid parent id");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WWriter.File.cs#L234)
* [ ] [CR2WWriter.File.cs#L314: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/CR2WWriter.File.cs#L314)
* [ ] [PackageReader.cs#L84: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Archive/IO/PackageReader.cs#L84)
* [ ] [scnAnimName.cs#L29: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Types/ClassesExt/Appendix/scnAnimName.cs#L29)
* [ ] [worldTrafficCompiledNode.cs#L25: TodoException($"Unknown value in {nameof(worldTrafficCompiledNode)}");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Types/ClassesExt/Appendix/worldTrafficCompiledNode.cs#L25)
* [ ] [gameSmartObjectAnimationDatabase.cs#L44: TodoException();](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.RED4.Types/ClassesExt/CustomData/gameSmartObjectAnimationDatabase.cs#L44)
* [x] [CurveEditorWindow.xaml.cs#L43: TodoException("CurveEditor");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Editors/CurveEditorWindow.xaml.cs#L43)
* [x] [CurveEditorWindow.xaml.cs#L541: TodoException("CurveEditor");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Editors/CurveEditorWindow.xaml.cs#L541)
* [ ] [HandleTemplateView.xaml.cs#L57: TodoException("handle editor");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Templates/HandleTemplateView.xaml.cs#L57)
* [ ] [HandleTemplateView.xaml.cs#L98: TodoException("handle editor");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Templates/HandleTemplateView.xaml.cs#L98)
* [ ] [HandleTemplateView.xaml.cs#L110: TodoException("handle editor");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Templates/HandleTemplateView.xaml.cs#L110)
* [x] [RedCurveEditor.xaml.cs#L37: TodoException("RedCurveEditor");](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Templates/RedCurveEditor.xaml.cs#L37)

**Comment by ADawesomeguy** [comment]
Hey @jackhumbert I think this is outdated and either is fixed, needs to be updated, or can be dropped as many of the files have changed drastically and some of them don't exist anymore.

**Comment by jackhumbert** [comment]
Yeah, I think we can close this for now, and address them as needed.
