### ISSUE TITLE
Implement proper graphs for easier editing of complex files.

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#79]
This library seems to be able to server our needs for editing behaviour files and complex w2l and such https://github.com/panthernet/GraphX
***
- [ ] Implement the basics of GraphX
- [ ] Replace the current cutscene editor
- [ ] Create a behaviour editor
- [ ] Create a flexible general CR2W graph editor which work with reflection
... etc. (Everything else should be discussed after these are done)

More costum editors:
- [x] HSL Color picker - This is coded but doesn't work for some reason.
- [ ] CCurve editor.
- [x] Also somehow rework the hex editor so it's easier to edit not explored stuff. Not sure about this how yet.

**Comment by Maxzor** [comment]
If there is something that I can like / ever do in this project that is this.

**Comment by Traderain** [comment]
I started playing around with this:
![image](https://user-images.githubusercontent.com/6411732/96705784-054ebb00-1396-11eb-8844-90752911d310.png)
I think its pretty doable to have some neat editor like radish has but we need some proper text serialization first. If I remember correctly we have csv or something. Does that work? @Maxzor what do you think?

**Comment by Maxzor** [comment]
I don't think the graph feature has any prerequisite to serialization matters.
Serialization is still in a poor shape but this is independent.
I vote for DearImGUI as a neat/KISS graph tool which allows for reusing rmemr's code.

**Comment by rfuzzo** [comment]
yes. this is still needed for RED4
